# Generated by Django 4.2.11 on 2024-09-01 13:22

from django.db import migrations
import os
from django.contrib.auth.hashers import make_password

def add_shop_owner(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Shop = apps.get_model('grill', 'Shop')
    MenuItem = apps.get_model('grill', 'MenuItem')
    Order = apps.get_model('grill', 'Order')
    Review = apps.get_model('grill', 'Review')
    OrderItem = apps.get_model('grill', 'OrderItem')

    isolafelice = User.objects.create(
        username='isolafelice',
        password=make_password(os.environ.get('TARGETSTAFFPASSWORD', '635da2776b8964490fe60516aca0bcbd')),
        is_staff=True
    )

    labrace = User.objects.create(
        username='labrace',
        password=make_password('46cedd9800ad9d56142d8980ace782a9'),
        is_staff=True
    )

    isolafelice = Shop.objects.create(name='Isola Felice', description='Italian restaurant', owner=isolafelice)
    labrace = Shop.objects.create(name='La Brace', description='Steakhouse', owner=labrace)

    MenuItem.objects.create(name='Arrosticini', description='Sheep arrosticini', price=1, shop=isolafelice)
    MenuItem.objects.create(name='Bruschetta', description='Grilled bread with olive oil', price=0.50, shop=isolafelice)
    MenuItem.objects.create(name='Vino rosso', description='Red wine', price=5, shop=isolafelice)

    MenuItem.objects.create(name='Arrosticini', description='Sheep arrosticini', price=1, shop=labrace)
    MenuItem.objects.create(name='Bruschetta', description='Grilled bread with olive oil', price=0.50, shop=labrace)
    MenuItem.objects.create(name='Vino bianco', description='White wine', price=6, shop=labrace)

    # Add order and review with the flag
    reviewuser = User.objects.create(
        username='reviewuser',
        password=make_password(os.environ.get('REVIEWUSERPASSWORD', 'ce27d2de649c2f2c8423663dc4b4103b'))
    )
    revieworder = Order.objects.create(shop=isolafelice, total=1, user=reviewuser)

    OrderItem.objects.create(order=revieworder, item=MenuItem.objects.get(name='Arrosticini', shop=isolafelice), quantity=10)
    OrderItem.objects.create(order=revieworder, item=MenuItem.objects.get(name='Bruschetta', shop=isolafelice), quantity=2)
    OrderItem.objects.create(order=revieworder, item=MenuItem.objects.get(name='Vino rosso', shop=isolafelice), quantity=1)

    Review.objects.create(order=revieworder, rating=5, comment=f'I loved the arrosticini so much, thank you :3 - {os.environ.get("FLAG", "MOCA{fakeflag}")}', user=reviewuser)


class Migration(migrations.Migration):

    dependencies = [
        ('grill', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_shop_owner),
    ]
